# Generated by Django 3.1.1 on 2021-09-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('idCancion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('esKaraoke', models.BooleanField()),
                ('artista', models.CharField(blank=True, max_length=60)),
                ('fechaPublicacion', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('letras', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('idLista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField()),
                ('canciones', models.ManyToManyField(to='Rockola.Cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=256)),
                ('fechaNacimiento', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rockola',
            fields=[
                ('idRockola', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('listas', models.ManyToManyField(to='Rockola.Lista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rockola.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rockola.usuario'),
        ),
    ]
