# Generated by Django 3.1.1 on 2021-09-29 22:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('idCancion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('fuente', models.CharField(max_length=256)),
                ('esKaraoke', models.BooleanField()),
                ('artista', models.CharField(blank=True, max_length=60)),
                ('fechaPublicacion', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('letras', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('idLista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField()),
                ('canciones', models.ManyToManyField(to='Rockola.Cancion')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('idPlaylist', models.AutoField(primary_key=True, serialize=False)),
                ('dateTimeAdded', models.DateTimeField(default=datetime.datetime.now)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rockola.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=256)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rockola',
            fields=[
                ('idRockola', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('canciones', models.ManyToManyField(blank=True, through='Rockola.PlayList', to='Rockola.Cancion')),
                ('listas', models.ManyToManyField(to='Rockola.Lista')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='rockola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rockola.rockola'),
        ),
    ]
