# Generated by Django 3.1.1 on 2021-09-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rockola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='fuente',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
