# Generated by Django 3.1.1 on 2021-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rockola', '0002_cancion_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockola',
            name='canciones',
            field=models.ManyToManyField(to='Rockola.Cancion'),
        ),
    ]
