# Generated by Django 3.2.7 on 2021-09-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rockola', '0002_cancion_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
