# Generated by Django 4.0 on 2021-12-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rockola', '0003_auto_20210929_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='cover',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='rockola',
            name='cover',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
