# Generated by Django 4.0 on 2021-12-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rockola', '0004_lista_cover_rockola_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='album',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
