# Generated by Django 4.0 on 2021-12-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rockola', '0005_cancion_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='artista',
            field=models.CharField(max_length=60),
        ),
    ]
