# Generated by Django 4.0 on 2021-12-29 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rockola', '0008_alter_lista_fechacreacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amigo',
            new_name='UserInfo',
        ),
    ]
