# Generated by Django 4.0 on 2021-12-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rockola', '0011_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fav_listas',
            field=models.ManyToManyField(blank=True, related_name='fav_listas', to='Rockola.Lista'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fav_rockolas',
            field=models.ManyToManyField(blank=True, related_name='fav_rockolas', to='Rockola.Rockola'),
        ),
    ]
