# Generated by Django 4.0 on 2021-12-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Rockola', '0012_userinfo_fav_listas_userinfo_fav_rockolas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitud',
            unique_together={('remitente', 'destinatario')},
        ),
    ]
