# Generated by Django 4.0 on 2021-12-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rockola', '0013_alter_solicitud_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
